version: '3.8'

services:
  # Service API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recofilm-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./mlruns:/app/mlruns
      - ./models:/app/models
    networks:
      - recofilm-network
    depends_on:
      - mlflow
    restart: unless-stopped

   # Service MLflow Server
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: recofilm-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    networks:
      - recofilm-network
    restart: unless-stopped

  

# Service Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: recofilm-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - recofilm-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: recofilm-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - recofilm-network
    depends_on:
      - prometheus
    restart: unless-stopped
  

# Volumes partagés
volumes:
  mlruns:
  models:
  prometheus_data: 
  grafana_data:

# Réseau interne avec IPv6 activé
networks:
  recofilm-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - subnet: fd00:dead:beef::/48