{
 "title": "project Recofilm",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temps de réponse (secondes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "Erreurs HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{status=\"4xx\"}"
    },
    {
     "expr": "http_requests_total{status=\"5xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes HTTP par seconde",
   "type": "timeseries",
   "description": "Taux de requêtes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Nombre de requêtes actives",
   "type": "timeseries",
   "description": "Nombre de requêtes HTTP en cours de traitement",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "http_requests_in_progress" }
   ]
  }
 ]
}